### ISSUE TITLE
Panel de control general, con información en tiempo real de los votantes de una votación

### ISSUE THREAD

**Issue by danieldml112** [DecideIO-Almacenamiento/decide-io-almacenamiento#1]
**Descripción de la característica**
Panel de control con estadísticas básicas de los votantes de una votación. En estas estadísticas se podrán ver:
* Sexo de los votantes.
* Segmentos de edades de los votantes.
* Origen de los votantes.

**Motivación**
Propuesta aceptada por el equipo desarrollador para la mejora del proyecto Decide. 

**Alternativas**
Ninguna. 

**Estado actual del sistema con respecto al nuevo funcionamiento**
No hay ningún panel de estadísticas parecido a la propuesta. Los usuarios votantes no tienen la información necesaria para la segmentación.

**Detalles adicionales**
Se deberá trabajar junto al módulo Autenticación para la obtención de los datos básicos de los votantes en su registro.

**Comment by danieldml112** [comment]
Se ha abierto la [incidencia](https://github.com/mansancab3/decide-io-auth/issues/4) de "Nueva propuesta" al módulo de autenticación.

**Comment by walviealv** [comment]
Se ha abierto la [indicencia](https://github.com/EGC-DECIDE-IO-Visualizacion/decide-io/issues/3) "Feature request" al módulo de visualización.

**Comment by walviealv** [comment]
**UPDATE**
Se requiere un cambio necesario propuesto por el equipo de visualización. (https://github.com/EGC-DECIDE-IO-Visualizacion/decide-io/issues/3#issuecomment-453772052)

**Comment by danieldml112** [comment]
> **UPDATE**
> Se requiere un cambio necesario propuesto por el equipo de visualización. ([EGC-DECIDE-IO-Visualizacion#3 (comment)](https://github.com/EGC-DECIDE-IO-Visualizacion/decide-io/issues/3#issuecomment-453772052))

Corregido en la liberación [v1.3.1](https://github.com/DecideIO-Almacenamiento/decide-io-almacenamiento/commits/v1.3.1)

Se han añadido 4 nuevas entradas en el JSON devuelto por la API:

- **"numero_edad_nsnc":** numero_edad_nsnc
   * Corresponde con el nº de usuarios del censo sin profile o edad en su profile.
- **"porcentaje_edad_nsnc":** porcentaje_edad_nsnc
   * Corresponde con el porcentaje de usuarios que han votado sin profile o edad en su profile sobre todos los del censo que tampoco tienen profile o edad en su profile.
- **"numero_sexo_nsnc":** numero_sexo_nsnc
   * Corresponde con el nº de usuarios del censo sin profile o sexo en su profile.
- **"porcentaje_sexo_nsnc":** porcentaje_sexo_nsnc
   * Corresponde con el porcentaje de usuarios que han votado sin profile o sexo en su profile sobre todos los del censo que tampoco tienen profile o sexo en su profile.

**Comment by danieldml112** [comment]
* La feature está ya integrada con la parte del módulo de Visualización.
* Por parte del módulo de Autenticación no se ha completado en tiempo suficiente para poder realizar la integración de su funcionalidad.
   * Aún así, con el "stub" realizado por nuestra parte para simular el profile de un usuario funciona correctamente.
   * Si fuese necesario, en un futuro se realizaría dicha integración con el módulo de Autenticación.
